### ISSUE TITLE
how to solve '175 invalid pixels in C:\Users\Xi Yu\Desktop\semantic-segmentation-baselines-master\src\datasets\camvid\y\test\data\Seq05VD_f02610_L.png'

### ISSUE THREAD

**Issue by yuxi120407** [Kautenja/semantic-segmentation-baselines#17]
we find that '175 invalid pixels in C:\Users\Xi Yu\Desktop\semantic-segmentation-baselines-master\src\datasets\camvid\y\test\data\Seq05VD_f02610_L.png' when generate data.

C:\Users\Xi Yu\Desktop\semantic-segmentation-baselines-master\src\datasets\_dataset.py:260: FutureWarning: read_table is deprecated, use read_csv instead.
  index_col='og'
C:\Users\Xi Yu\Desktop\semantic-segmentation-baselines-master\src\datasets\_label_colors.py:22: FutureWarning: read_table is deprecated, use read_csv instead.
  label_map = pd.read_table(map_file, sep=r'\s+', names=names)
 21%|████████████████▎                                                            | 149/701 [01:26<05:31,  1.67image/s]

WARNING: 175 invalid pixels in C:\Users\Xi Yu\Desktop\semantic-segmentation-baselines-master\src\datasets\camvid\y\test\data\Seq05VD_f02610_L.png

**Comment by Kautenja** [comment]
Can't; that's just how the CamVid dataset is. the data loader suppresses the issue by labeling the pixels as void. It's only 175 pixels anyway.
